# Generated by Django 5.0.6 on 2024-06-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.BigIntegerField(default=0)),
                ('sum', models.BigIntegerField(default=0)),
                ('post_id', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['post_id'], name='rating_api__post_id_d223b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['post_id'], name='rating_api__post_id_842da8_idx'), models.Index(fields=['post_id', 'user_id'], name='rating_api__post_id_f13dc9_idx')],
            },
        ),
    ]
