# Generated by Django 5.0.6 on 2024-06-14 09:34

import rating_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED')], default=rating_api.models.RatingStatus['APPROVED'], max_length=255),
        ),
    ]
